main: com.madcreeper11.MCMiniGames.PluginMain
name: MCMiniGames
api-version: 1.21.5
version: 1
description: Includes a range of different minigames
author: madcreeper11
commands:
 teams:
  description: Shows the current team composition
  aliases:
  permission: huntersVsSpeedrunners.teams
  permission-message: You do not have permission!
  usage: /<command>
  
 team:
  description: Allows changes to the teams
  aliases:
  permission: huntersVsSpeedrunners.team
  permission-message: You do not have permission!
  usage: /<command> [speedrunner/hunter] [add/remove] {user1, user2...}
  
 hvs:
  description: Dictates the HuntersVsSpeedrunners game state
  aliases:
  permission: huntersVsSpeedrunners.game
  permission-message: You do not have permission!
  usage: /<command> [start/stop]
  
 randomItemPVP:
  description: Dictates the game state
  aliases:
  permission: randomItemPVP.game
  permission-message: You do not have permission!
  usage: /<command> [start/stop]
  
 ds:
  description: Dictates the game state for deathswap
  aliases:
  permission: deathSwap.game
  permission-message: You do not have permission!
  usage: /<command> [start/stop]
   
permissions:
 huntersVsSpeedrunners.teams:
  description: Allows teams command
  default: op
 huntersVsSpeedrunners.team:
  description: Allows team command
  default: op
 huntersVsSpeedrunners.game:
  description: Allows game command
  default: op
 huntersVsSpeedrunners.*:
  description: Wildcard permission
  default: op
  children:
 randomItemPVP.game:
  description: Allows game command
  default: op
 randomItemPVP.*:
  description: Wildcard permission
  default: op
  children:
 ds.game:
  description: Allows game command
  default: op
  children: