main: com.madcreeper11.MCMiniGames.PluginMain
name: MCMiniGames
api-version: 1.21.5
version: 1
description: Includes a range of different minigames
author: madcreeper11
commands:  
 ds:
  description: Dictates the game state for deathswap.
  usage: /ds [start/stop]
  permission: deathSwap.game
  permission-message: You do not have permission to use this command.
  aliases: [deathswap, ds]